# ---------------------------------------------------------------
# Jekyll & Global Configuration
## Docs: https://jekyllrb.com/docs/configuration/
# ---------------------------------------------------------------

# Site
title: Pre-Demo-Field
subtitle: DeamoV's Blog
description: Work Hard! Play Hard!
author: DeamoV

# Support language: de, en, fr-FR, id, ja, ko, pt-BR, pt, ru, zh-Hans, zh-hk, zh-tw
language: zh
date_format: '%Y-%m-%d'
